# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Xu9PKbeiQJm8QEmKG5anUyI7qg5PB6o
"""

# archivo_analisis_generico.py
import csv

# ---------------------
# 1. Leer archivo CSV
# ---------------------
def leer_csv(nombre_archivo, columnas=('especie', 'año', 'cantidad')):
    """
    Lee un archivo CSV y devuelve una lista de diccionarios
    donde cada diccionario representa una fila del archivo.
    columnas: tupla con los nombres de las columnas a usar
    """
    datos = []

    try:
        with open(nombre_archivo, 'rt') as f:
            lector = csv.reader(f)
            next(lector)  # saltar encabezado

            for n_fila, fila in enumerate(lector, start=2):
                if not fila:
                    continue
                try:
                    fila_dict = {
                        columnas[0]: fila[0],
                        columnas[1]: int(fila[1]),
                        columnas[2]: float(fila[2])
                    }
                    datos.append(fila_dict)
                except ValueError:
                    print(f"Fila {n_fila}: error con {fila}")
    except FileNotFoundError:
        print("Archivo no encontrado:", nombre_archivo)

    return datos

# ---------------------
# 2. Filtrar datos opcionales
# ---------------------
def filtrar_datos(lista_diccionarios, columna_a_filtrar=None, dato_a_filtrar=None):
    """
    Filtra la lista de diccionarios por un valor específico en una columna
    """
    resultado = []
    for fila in lista_diccionarios:
        if columna_a_filtrar and fila[columna_a_filtrar] != dato_a_filtrar:
            continue
        resultado.append(fila)
    return resultado

# ---------------------
# 3. Sumar columna
# ---------------------
def suma_columna(lista_diccionarios, columna_suma):
    return sum(fila[columna_suma] for fila in lista_diccionarios)

# ---------------------
# 4. Agrupar por columna
# ---------------------
def agrupar_por_columna(lista_diccionarios, columna_agrupar, columna_valor):
    dic = {}
    for fila in lista_diccionarios:
        clave = fila[columna_agrupar]
        dic[clave] = dic.get(clave, 0) + fila[columna_valor]
    return dic

# ---------------------
# 5. Máximo y mínimo en diccionario
# ---------------------
def clave_maximo(dic):
    return max(dic, key=dic.get) if dic else None

def clave_minimo(dic):
    return min(dic, key=dic.get) if dic else None

# ---------------------
# 6. Elementos que aparecen todos los años (o todos los valores)
# ---------------------
def elementos_todos_valores(lista_diccionarios, columna_agrupar, columna_filtro):
    todos_valores = set(fila[columna_filtro] for fila in lista_diccionarios)
    agrupados = {}

    for fila in lista_diccionarios:
        clave = fila[columna_agrupar]
        agrupados.setdefault(clave, set()).add(fila[columna_filtro])

    return [clave for clave, valores in agrupados.items() if valores == todos_valores]

# ---------------------
# 7. Elementos únicos
# ---------------------
def elementos_unicos(lista_diccionarios, columna):
    contador = {}
    for fila in lista_diccionarios:
        valor = fila[columna]
        contador[valor] = contador.get(valor, 0) + 1
    return [valor for valor, cant in contador.items() if cant == 1]

# ---------------------
# 8. Programa principal
# ---------------------
def main():
    nombre_archivo = input("Nombre archivo CSV: ").strip()

    columna_agrupar = 'especie'  # columna principal para agrupar
    columna_valor = 'cantidad'   # columna numérica a sumar
    columna_filtro_año = 'año'   # columna opcional a filtrar

    dato_a_filtrar_columna = input(f"Valor a filtrar en {columna_agrupar} (opcional): ").strip()
    dato_a_filtrar_año = input(f"Valor a filtrar en {columna_filtro_año} (opcional): ").strip()

    if dato_a_filtrar_columna == "":
        dato_a_filtrar_columna = None
    if dato_a_filtrar_año == "":
        dato_a_filtrar_año = None
    else:
        try:
            dato_a_filtrar_año = int(dato_a_filtrar_año)
        except ValueError:
            print("Año inválido")
            return

    datos = leer_csv(nombre_archivo, columnas=(columna_agrupar, columna_filtro_año, columna_valor))
    if not datos:
        print("No hay datos para analizar.")
        return

    # Aplicar filtros opcionales
    datos_filtrados = filtrar_datos(datos, columna_agrupar, dato_a_filtrar_columna)
    datos_filtrados = filtrar_datos(datos_filtrados, columna_filtro_año, dato_a_filtrar_año)

    print("\n--- RESULTADOS ---\n")
    print("Total", columna_valor + ":", suma_columna(datos_filtrados, columna_valor))

    por_grupo = agrupar_por_columna(datos_filtrados, columna_agrupar, columna_valor)
    por_valor = agrupar_por_columna(datos_filtrados, columna_filtro_año, columna_valor)

    print(f"{columna_agrupar} más alto:", clave_maximo(por_grupo))
    print(f"{columna_agrupar} más bajo:", clave_minimo(por_grupo))

    print(f"{columna_filtro_año} con más total:", clave_maximo(por_valor))
    print(f"{columna_filtro_año} con menos total:", clave_minimo(por_valor))

    print(f"{columna_agrupar} presentes todos los {columna_filtro_año}:", elementos_todos_valores(datos_filtrados, columna_agrupar, columna_filtro_año))
    print(f"{columna_agrupar} únicos:", elementos_unicos(datos_filtrados, columna_agrupar))
    print("\n-----------------\n")

if __name__ == "__main__":
    main()